POST http://localhost:5000/todos/addtodo
Content-Type: application/json

{
    "name":"harke",
    "important":"true",
    "complete":"true",
    "userID":"12220"
    
}

###

POST http://localhost:5000/users/signup
Content-Type: application/json

{
    "fullname":"true",
    "email":"true",
    "password":"true",
    "phoneNumber":"true"    
}


###

GET http://localhost:5000/users/getuser
Content-Type: application/json

{

}


###