POST http://localhost:5000/todos/addtodo
Content-Type: application/json

{
    "name":"harke",
    "important":"true",
    "complete":"true",
    "userID":"12220"
    
}

###

POST http://localhost:5000/users/signup
Content-Type: application/json

{
    "fullname":"true",
    "email":"true",
    "password":"true",
    "phoneNumber":"true"    
}


###

POST  http://localhost:5000/todos/gettodo
Content-Type: application/json

{
  "userID": "63867e80e2fe63d5a4f6c812"
}


###


POST http://localhost:5000/todos/toggletodo
Content-Type: application/json

{
    "_id": "63867e80e2fe63d5a4f6c812"
    
}

###

POST http://localhost:5000/todos/deletetodo
Content-Type: application/json

{
    "userID": "63867e80e2fe63d5a4f6c812",
    "complete":"false"

    
}

###